### ISSUE TITLE
Error: error in tree: too many species in tree.

### ISSUE THREAD

**Issue by YDD99** [dosreislab/mcmc3r#13]
singularity  exec "/home/xly/soft/PhyloTools.sif" mcmctree mcmctree.ctl > run.log

Error: error in tree: too many species in tree.

**Comment by mariodosreis** [comment]
Closing this issue as it is not an `mcmc3r` issue but rather an `mcmctree` one. 

It looks like you may be trying to use a tree that has more species than the default for the program. You can edit the source code to increase the maximum number of taxa and recompile. You can get more help on this on the PAML google forums. If the error persits, please report it to the PAML github repository: 

[https://github.com/abacus-gene/paml]()

Please also follow best practice for the reporting of bugs:

[https://www.softwaretestinghelp.com/how-to-write-good-bug-report/]()
