### ISSUE TITLE
Delete inactive branches

### ISSUE THREAD

**Issue by mariodosreis** [dosreislab/mcmc3r#7]
@sabifo4 Branch `tidymorpho` is inactive and should be deleted if not in use. Ideally, we should only have `master` and `dev` branches. This is an issue request to perform general maintenance of the package.

**Comment by mariodosreis** [comment]
@sabifo4 any progress on this?

**Comment by sabifo4** [comment]
I have not had time to go through this yet. Will work on this issue this week and will close it when it is resolved!

**Comment by mariodosreis** [comment]
@sabifo4 inactive branches `morpho` and `dev` have been deleted. This issue is now closed.
